spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: demo
  password: demo

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    history-level: "no-sql-history"

data:
  mongodb:
    host: localhost
    port: 27017